name: flutter_project_initializer
description: A Flutter project starter template inspired by Spring Initializr.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
